import { context } from "@actions/github";
import { writeFileSync } from "fs";
import { deleteMeMessage } from "./deleteMePrMessage";

export const deleteFile = 'DELETE_ME.md';

export function addDeleteMeFile(branch: string) {

  writeFileSync(deleteFile, [
    ":warning::warning::warning:",
    "Delete this file before merging a PR.",
    "Why do we have this?",
    "Because PRs created automatically by `rg-changeset` won't trigger PR actions. By manually deleting this file, you will trigger the required PR actions.",
    ":octocat: File generated by rg-changeset.",
    ":warning::warning::warning:",
  ].join('\n\n'));

  return deleteMeMessage(branch);

}